### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Godfather133th** [r0ttenbeef/SIEMPack#1]
Hi,

I faced issue during installation(actually with MISP), I'm using ubuntu v 20

Step 30/42 : RUN bash INSTALL_NODB.sh -A -u
 ---> Running in 9871ca44efb0
sha1 matches
sha256 matches
sha384 matches
sha512 matches
tput: No value for $TERM and no -T specified
-
The following DB Passwords were generated...
Admin (root) DB Password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
User  (misp) DB Password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
all
unattended
    Either your platform is not easily detectable or is not supported by this
    installer script.
    Please visit the following URL for more detailed installation instructions:
    https://misp.github.io/MISP/
ERROR: Service 'misp' failed to build: The command '/bin/sh -c bash INSTALL_NODB.sh -A -u' returned a non-zero code: 1

**Comment by r0ttenbeef** [comment]
Sorry for the late reply,
This issue appeared after ubuntu jammy has been released as misp supports ubuntu until focal so I have made a change to Dockerfile to download ubuntu:20.04 specifically instead of ubuntu:latest and it has been fixed.
